version: "3.5"
services:
  bootnode:
    image: coqchain:latest
    command:
      - "--datadir=/datadir/node"
      - "--syncmode=full"
      - "--networkid=9705"
      - "--nodekeyhex=c199a45cba57765a132004bf330ad868ef51335b64e0693458d2282c67f2d24b"
      - "--maxpeers=512"
      - "--light.maxpeers=256"
      - "--light.serve=50"
      - "--miner.gaslimit=30000000"
      - "--txpool.accountslots=256"
      - "--txpool.globalslots=10000"
      - "--txpool.accountqueue=128"
      - "--txpool.globalqueue=5000"
    volumes:
      - "./data/bootnode:/datadir/node"
    ports:
      - "30303:30303"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "10"
    networks:
      - coqchain-local

  validator_1:
    image: coqchain:latest
    command:
      - "--datadir=/datadir/node"
      - "--networkid=9705"
      - "--txlookuplimit=0"
      - "--mine"
      - "--syncmode=full"
      - "--allow-insecure-unlock"
      - "--unlock=0bfa300c5e3ae73dce81fe95653e80aa88f1aacc"
      - "--password=/password.txt"
      - "--config=/config.toml"
      - "--miner.gaslimit=30000000"
      - "--txpool.accountslots=256"
      - "--txpool.globalslots=10000"
      - "--txpool.accountqueue=128"
      - "--txpool.globalqueue=5000"
    volumes:
      - "./data/validator_1:/datadir/node"
      - "./password.txt:/password.txt"
      - "./config.toml:/config.toml"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "10"
    networks:
      - coqchain-local

  validator_2:
    image: coqchain:latest
    command:
      - "--datadir=/datadir/node"
      - "--networkid=9705"
      - "--txlookuplimit=0"
      - "--mine"
      - "--syncmode=full"
      - "--allow-insecure-unlock"
      - "--unlock=df46be5ec52bb359c84140aed6cad8074960d8c9"
      - "--password=/password.txt"
      - "--config=/config.toml"
      - "--miner.gaslimit=30000000"
      - "--txpool.accountslots=256"
      - "--txpool.globalslots=10000"
      - "--txpool.accountqueue=128"
      - "--txpool.globalqueue=5000"
    volumes:
      - "./data/validator_2:/datadir/node"
      - "./password.txt:/password.txt"
      - "./config.toml:/config.toml"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "10"
    networks:
      - coqchain-local

  validator_3:
    image: coqchain:latest
    command:
      - "--datadir=/datadir/node"
      - "--networkid=9705"
      - "--txlookuplimit=0"
      - "--mine"
      - "--syncmode=full"
      - "--allow-insecure-unlock"
      - "--unlock=5da5b8cc83285ec3defef17dd335bdfae5898214"
      - "--password=/password.txt"
      - "--config=/config.toml"
      - "--miner.gaslimit=30000000"
      - "--txpool.accountslots=256"
      - "--txpool.globalslots=10000"
      - "--txpool.accountqueue=128"
      - "--txpool.globalqueue=5000"
    volumes:
      - "./data/validator_3:/datadir/node"
      - "./password.txt:/password.txt"
      - "./config.toml:/config.toml"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "10"
    networks:
      - coqchain-local

  rpc:
    image: coqchain:latest
    command:
      - "--datadir=/datadir/node"
      - "--networkid=9705"
      - "--txlookuplimit=0"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,txpool,personal"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.api=eth,net,web3,debug,txpool,personal"
      - "--ws.port=8546"
      - "--ws.origins=*"
      - "--syncmode=full"
      - "--gcmode=archive"
      - "--allow-insecure-unlock"
      - "--config=/config.toml"
      - "--miner.gaslimit=30000000"
      - "--txpool.accountslots=256"
      - "--txpool.globalslots=10000"
      - "--txpool.accountqueue=128"
      - "--txpool.globalqueue=5000"
    volumes:
      - "./data/rpc:/datadir/node"
      - "./config.toml:/config.toml"
    restart: always
    ports:
      - "8545:8545"
      - "8546:8546"
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "10"
    networks:
      - coqchain-local
      
  faucet:
    image: faucet:latest
    command:
      - "--genesis=/genesis.json"
      - "--bootnodes=enode://c81dd5f432557819de79c21d59b50f84463a746ada3f900ba63364fa9de062bde2637d35627d1af9514e347e4f8e0495691bc783e1f996c402400840199f4841@bootnode:30303"
      - "--network=9705"
      - "--account.json=/root/.faucet/UTC--2022-08-25T08-41-43.342038531Z--5da5b8cc83285ec3defef17dd335bdfae5898214"
      - "--account.pass=/password.txt"
      - "--noauth=true"
      - "--faucet.name=COQ"
      - "--faucet.amount=10"
      - "--faucet.tiers=5"
    ports:
      - "3000:8080"
    volumes:
      - "./genesis.json:/genesis.json"
      - "./password.txt:/password.txt"
      - "./faucet:/root/.faucet"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "10"
    networks:
      - coqchain-local
      
networks:
   coqchain-local:
       driver: bridge
       ipam:
         driver: default
         config:
           - subnet: 172.16.200.0/24
